[package]
name = "app-activate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
env_logger = "0.11.5"
global-hotkey = "0.6.2"
log = "0.4.22"
open = "5.3.0"
serde = "1.0.213"
toml = "0.8.19"
winit = "0.29.15"
