leader_key = "F10" # A hotkey to trigger the launcher
timeout_ms = 600 # The time in milliseconds to wait for the next key press

# A pair of second hotkey and absolute path to the application
[applications]
c = "/System/Applications/Calendar.app" # means that pressing the `leader_key`, (releasing it), and then pressing `c` within the `timeout_ms` will open the Calendar app
f = "/Applications/Firefox.app"
g = "/Applications/Google Chrome.app"
i = "/System/Library/CoreServices/Finder.app"
s = "/Applications/Slack.app"
t = "/Applications/Ghostty.app"
